import { StyleSheet } from 'react-native'
import {COLORS, FONTSIZE} from '../../../themes/Theme'

const PaymentStyles = StyleSheet.create({

    payementMainContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.generalBackgroundBlack,
    },
    paymenMainText: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        color: COLORS.primaryWhite,
        fontFamily: 'Poppins',
        fontSize: FONTSIZE.size_28,
        fontWeight: 'bold',
    },
    paymentInnerContainer: {
        flex: 1,
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.generalBackgroundBlack,
    },
    paymentCardContainer: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        width: 340,
        height: 280,
        marginTop: 20,
        borderColor: COLORS.primaryOrange,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        backgroundColor: COLORS.generalBackgroundBlack,
    },
    paymentCardGradient: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        height: 220,
        marginTop: 20,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
    },
    paymentCard: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        marginTop: 20,
        padding: 10,
    },
    paymentDataTitles: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        color: COLORS.primaryWhite,
        fontFamily: 'Poppins',
        fontSize: FONTSIZE.size_14,
    },
    
    paymentInputUser: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        width: 340,
        height: 60,
        marginTop: 20,
        borderColor: COLORS.primaryOrange,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        backgroundColor: COLORS.generalBackgroundBlack,
        color: COLORS.primaryWhite,
        fontFamily: 'Poppins',
        fontSize: FONTSIZE.size_14,
    },
    paymentButtonContainer: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        marginTop: 20,
        padding: 10,
    },
    paymentButton: {
        flexDirection: 'column',
        position: 'relative',
        alignContent: 'center',
        justifyContent: 'center',
        width: 340,
        height: 60,
        marginTop: 20,
        borderColor: COLORS.primaryOrange,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        backgroundColor: COLORS.primaryOrange,
    },

});

export default PaymentStyles;